### PR TITLE
DPR-422 Jobs code refactor pass 2

### PR DESCRIPTION
**Pull request by carwynmoj**
Summary of changes
* renamed `TableInfo` to `HiveTableIdentifier` which should better reflect the intent of this class
* simplified `ResourceLoader`
* cleaned up `DomainExecutorTest` removing duplication where possible, simplified `areEqual` and used `val` keyword instead of explicit type declarations
* other minor tidyups

### CODE REVIEW

**Review by dominic-messenger-moj — COMMENTED** [review]
I don't think HiveTableIdentifier is the right intent. TableInfo is about the logical table (reflected on Disk in DeltaLake, or Hudi, or Iceberg, or event Postgres) and it happens to also be used to apply metadata somewhere (not just Hive, although that is an implementation). It is shared across both.

**Review by kartthik-n — COMMENTED** [review]
Unable to run the glue job. resulting in the below exception. It seems some issue with the dependency injection

2023-05-10 22:19:50,172 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(77)): Exception in User Class: java.lang.reflect.UndeclaredThrowableException
org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1894)
org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:471)
org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:460)
org.apache.spark.executor.CoarseGrainedExecutorBackendPlugin.launch(CoarseGrainedExecutorBackendWrapper.scala:10)
org.apache.spark.executor.CoarseGrainedExecutorBackendPlugin.launch$(CoarseGrainedExecutorBackendWrapper.scala:10)
org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper$$anon$1.launch(CoarseGrainedExecutorBackendWrapper.scala:15)
org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper.launch(CoarseGrainedExecutorBackendWrapper.scala:19)
org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper$.main(CoarseGrainedExecutorBackendWrapper.scala:5)
org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper.main(CoarseGrainedExecutorBackendWrapper.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.amazonaws.services.glue.SparkProcessLauncherPlugin.invoke(ProcessLauncher.scala:50)
com.amazonaws.services.glue.SparkProcessLauncherPlugin.invoke$(ProcessLauncher.scala:50)
com.amazonaws.services.glue.ProcessLauncher$$anon$1.invoke(ProcessLauncher.scala:92)
com.amazonaws.services.glue.ProcessLauncher.launch(ProcessLauncher.scala:163)
com.amazonaws.services.glue.ProcessLauncher$.main(ProcessLauncher.scala:30)
com.amazonaws.services.glue.ProcessLauncher.main(ProcessLauncher.scala)

**Comment by carwynmoj** [comment]
> Unable to run the glue job. resulting in the below exception. It seems like some issue with the dependency injection
> 
> 2023-05-10 22:19:50,172 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(77)): Exception in User Class: java.lang.reflect.UndeclaredThrowableException org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1894) org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61) org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:471) org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:460) org.apache.spark.executor.CoarseGrainedExecutorBackendPlugin.launch(CoarseGrainedExecutorBackendWrapper.scala:10) org.apache.spark.executor.CoarseGrainedExecutorBackendPlugin.launch$(CoarseGrainedExecutorBackendWrapper.scala:10) org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper$$anon$1.launch(CoarseGrainedExecutorBackendWrapper.scala:15) org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper.launch(CoarseGrainedExecutorBackendWrapper.scala:19) org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper$.main(CoarseGrainedExecutorBackendWrapper.scala:5) org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper.main(CoarseGrainedExecutorBackendWrapper.scala) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.amazonaws.services.glue.SparkProcessLauncherPlugin.invoke(ProcessLauncher.scala:50) com.amazonaws.services.glue.SparkProcessLauncherPlugin.invoke$(ProcessLauncher.scala:50) com.amazonaws.services.glue.ProcessLauncher$$anon$1.invoke(ProcessLauncher.scala:92) com.amazonaws.services.glue.ProcessLauncher.launch(ProcessLauncher.scala:163) com.amazonaws.services.glue.ProcessLauncher$.main(ProcessLauncher.scala:30) com.amazonaws.services.glue.ProcessLauncher.main(ProcessLauncher.scala)

Shouldn't be a DI issue since Micronaut resolves deps at compile time. I'll take a look and fix it.

**Comment by carwynmoj** [comment]
> > Unable to run the glue job. resulting in the below exception. It seems like some issue with the dependency injection
> > 2023-05-10 22:19:50,172 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(77)): Exception in User Class: java.lang.reflect.UndeclaredThrowableException org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1894) org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61) org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:471) org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:460) org.apache.spark.executor.CoarseGrainedExecutorBackendPlugin.launch(CoarseGrainedExecutorBackendWrapper.scala:10) org.apache.spark.executor.CoarseGrainedExecutorBackendPlugin.launch$(CoarseGrainedExecutorBackendWrapper.scala:10) org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper$$anon$1.launch(CoarseGrainedExecutorBackendWrapper.scala:15) org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper.launch(CoarseGrainedExecutorBackendWrapper.scala:19) org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper$.main(CoarseGrainedExecutorBackendWrapper.scala:5) org.apache.spark.executor.CoarseGrainedExecutorBackendWrapper.main(CoarseGrainedExecutorBackendWrapper.scala) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.amazonaws.services.glue.SparkProcessLauncherPlugin.invoke(ProcessLauncher.scala:50) com.amazonaws.services.glue.SparkProcessLauncherPlugin.invoke$(ProcessLauncher.scala:50) com.amazonaws.services.glue.ProcessLauncher$$anon$1.invoke(ProcessLauncher.scala:92) com.amazonaws.services.glue.ProcessLauncher.launch(ProcessLauncher.scala:163) com.amazonaws.services.glue.ProcessLauncher$.main(ProcessLauncher.scala:30) com.amazonaws.services.glue.ProcessLauncher.main(ProcessLauncher.scala)
> 
> Shouldn't be a DI issue since Micronaut resolves deps at compile time. I'll take a look and fix it.

spark-core is deliberately excluded from the build since it's provided by aws glue. The intent here is to keep the jar size down since it's already rather large. I intend to review this later to see if there's anything else that can be removed.

**Review by dominic-messenger-moj — APPROVED** [review]
Approved. I prefer finals on parameters as it is explicit the caller isn't going to change values, but that's a preference

**Review by dominic-messenger-moj — APPROVED** [review]
Approved. I prefer finals on parameters as it is explicit the caller isn't going to change values, but that's a preference

**Pull request merged**
